telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME}
    token: ${TELEGRAM_BOT_TOKEN}

yandex:
  cloud:
    translation:
      url: 'https://translate.api.cloud.yandex.net/translate/v2'
      folderId: ${YANDEX_CLOUD_FOLDER_ID}
    token:
      url: 'https://iam.api.cloud.yandex.net/iam/v1'
      authorizationToken: ${YANDEX_CLOUD_AUTHORIZATION_TOKEN}
      delayBeforeRefreshInMillis: 10800000 # 3 hours

app:
  hashtags:
    - hashtag: '#перевод'
      sourceLanguage: 'tt'
      targetLanguage: 'ru'
    - hashtag: '#тәрҗемә'
      sourceLanguage: 'ru'
      targetLanguage: 'tt'
