telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME}
    token: ${TELEGRAM_BOT_TOKEN}

yandex:
  cloud:
    translationUrl: 'https://translate.api.cloud.yandex.net/translate/v2'
    folderId: ${YANDEX_CLOUD_FOLDER_ID}
    authorizationToken: ${YANDEX_CLOUD_AUTHORIZATION_TOKEN}

app:
  markers: ['#перевод', '#тәрҗемә']
